### ISSUE TITLE
controller load error

### ISSUE THREAD

**Issue by Hughshy** [skywoodsz/qm_control#10]
**Hi！Thanks for your share, i have some trouble when I run the code.**

When i launch the controller by using "_roslaunch qm_controllers load_controller.launch_",  Error occur,
`process[controller_loader-1]: started with pid [109660]
Loaded 'controllers/joint_state_controller'
Loaded 'controllers/qm_controller'
[controller_loader-1] process has finished cleanly
log file: /home/xxx/.ros/log/14b469aa-b550-11ee-ad02-d76696754dc5/controller_loader-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done`

When i launch the controller by using "_mon launch qm_controllers load_controller.launch_", Error occur,
`could not open pipe to mail: No such file or directory`

I'm very confuse about this, Looking forward to your reply！！！

**Comment by skywoodsz** [comment]
@Hughshy 
Thanks for your follow. It seems you don't source the environment or don't install the ros-controller.
You can solve this problem by:
`sudo apt-get install ros-noetic-ros-control ros-noetic-ros-controllers`
`source <your-workspace>/devel/setup.bash`

**Comment by Hughshy** [comment]
Thanks for your reply,  after install the **ros-noetic-ros-controllers**, the error changed,
run `mon launch qm_controllers load_controller.launch`, shell return nothing.
when i  search on the google, very lucky to find answers. the reason is this desktop don't install **rosmon**
install the **rosmon** by
`sudo apt install ros-noetic-rosmon ` 
`source /opt/ros/noetic/setup.bash` 
everthing is ok!
