### ISSUE TITLE
Problem when changing aliengo to unitree B1

### ISSUE THREAD

**Issue by OceansDepp** [skywoodsz/qm_control#13]
Hi! Thank you for sharing the project! I am trying to change the quadruped robot from aliengo to B1 (whose trunk is about 25kg). I successfully change the robot model and run the whole pipeline (by creating a new const.xacro for b1 robot and edit the robot.xacro), but find some problems in controlling the base. When given a goal point of ee, the base is not able to stand up (it seems that the torque of the motors is too small to hold the body up). I did try to tune the weights in task.info and wbcWeight.cfg file, but it still won't work. Therefore, I wonder could you please give me some suggestion on how to solve this problem? I really appreciate it if you could give my some advice based on your understanding of the project.

**Comment by OceansDepp** [comment]
issue solved!

**Comment by javierpey** [comment]
Hi @OceansDepp, how did you solve the issue? I was thinking about using Unitree B1 too. Thank you in advance!

**Comment by skywoodsz** [comment]
@OceansDepp 
Thanks for your follow! 

I recommend replacing robot urdf with your robot urdf.  

For your question, I suggest you turn `recompileLibrariesCppAd` to the true in the `task.info`. In this way, the new weight in MPC can work.
