### ISSUE TITLE
更换机械臂为unitree_z1后出现的一些问题

### ISSUE THREAD

**Issue by nanyangnuan** [skywoodsz/qm_control#17]
感谢你分享这个项目。
但是我将机械臂更换为unitree_z1后，出现了一些问题，目标的初始朝向指向y负轴（假设前进方向为x正轴）。更改QMController.cpp中EeInitTarget的姿态和QmTargetTrajectoriesPublisher.cpp中interactiveMarker的姿态，目标的初始朝向指向了x正轴，但是当我更改目标位置并send target pose后，gazebo显示ERROR:  
 /gazebo: Maximum number of working set recalculations performed
 /gazebo: ERROR:  Premature homotopy termination because QP is infeasible
 /gazebo: ->ERROR:  Initial QP could not be solved due to infeasibility!
![589C7E2C2A597305A4938B358DD317ED](https://github.com/user-attachments/assets/14b2b901-f0ad-46c5-84cc-6d834ae3622a)

我看到你在问题#14中提到可以更改task.info 和 reference.info中的初始状态和目标值，请问具体操作是什么？
再次感谢你的分享

**Comment by danisotelo** [comment]
Hi @nanyangnuan! I just uploaded a project where I implemented this controller with the Z1 manipulator: https://github.com/danisotelo/qm_door. I don't get this issue so maybe its helpful to you!

**Comment by nanyangnuan** [comment]
@danisotelo Thank you for your selfless sharing. Actually the above problem has been solved. But other problems appeared, rviz often flashes back when operating in rviz interface. I believe your sharing will solve my problem.
