### ISSUE TITLE
怎么在仿真里运动？

### ISSUE THREAD

**Issue by biosbeta** [skywoodsz/qm_control#3]
请问怎么在仿真里怎么发送运动指令？能给一个例子吗，谢谢

**Comment by skywoodsz** [comment]
Thanks for your follow!
You can watch the tutorial video.
**Video Links:** [YouTube](https://youtu.be/JCn5obOh4D8), [bilibili](https://www.bilibili.com/video/BV1uP411v7Ab) (for China).

**Comment by skywoodsz** [comment]
> 请问怎么在仿真里怎么发送运动指令？能给一个例子吗，谢谢

Thanks for your follow!
You can watch the tutorial video.
Video Links: [YouTube](https://youtu.be/JCn5obOh4D8), [bilibili](https://www.bilibili.com/video/BV1uP411v7Ab) (for China).

**Comment by skywoodsz** [comment]
> 请问怎么在仿真里怎么发送运动指令？能给一个例子吗，谢谢

If you do not have other questions, I will close this issue.
