### ISSUE TITLE
could not open pipe to mail: No such file or directory

### ISSUE THREAD

**Issue by dbdxnuliba** [skywoodsz/qm_control#4]
rb@rb-System-Product-Name:~/ref/ws_qm_control$ mon launch qm_controllers load_controller.launch
could not open pipe to mail: No such file or directory

**Comment by skywoodsz** [comment]
> rb@rb-System-Product-Name:~/ref/ws_qm_control$ mon launch qm_controllers load_controller.launch could not open pipe to mail: No such file or directory

It looks like you didn't execute the command: 
`source <your_workspace>/devel/setup.bash`

**Comment by dbdxnuliba** [comment]
source之后运行mon launch 没啥反映
![image](https://github.com/skywoodsz/qm_control/assets/13350158/9556c5cf-b9e2-4a2c-9515-b02ec375a365)

**Comment by skywoodsz** [comment]
You can follow the video tutor: [YouTube](https://youtu.be/JCn5obOh4D8), [bilibili](https://www.bilibili.com/video/BV1uP411v7Ab) (for China). If the problem cannot be solved, please send me an email to get my WeChat.

> source之后运行mon launch 没啥反映 ![image](https://user-images.githubusercontent.com/13350158/269907835-9556c5cf-b9e2-4a2c-9515-b02ec375a365.png)

You can follow the video tutor: [YouTube](https://youtu.be/JCn5obOh4D8), [bilibili](https://www.bilibili.com/video/BV1uP411v7Ab) (for China). If the problem cannot be solved, please send me an email to get my WeChat.

**Comment by dbdxnuliba** [comment]
thanks a lot

**Comment by wss20030128** [comment]
~/catkin_ws$ mon launch qm_gazebo empty_world.launch
could not open pipe to mail: No such file or directory
