### ISSUE TITLE
Slow motion issues caused by HierarchicalWbc

### ISSUE THREAD

**Issue by ChenZheng29** [skywoodsz/qm_control#5]
Hello, this is a great project. Thank you for your open source project!
During the process of running your project, I encountered a problem. Have you ever encountered a situation where the RealTIMeRector of Gazebo is very small, manifested as the robot moving in slow motion, as shown in the following figure:
![2023-09-21 14-49-01屏幕截图](https://github.com/skywoodsz/qm_control/assets/58427883/d9e9fadc-01fb-4ca5-9470-d54a4ae80ff1)
Later, compared to legged_ Robot, it was found that it was caused by HierarchicalWbc, while WeightedWbc did not. When using HierarchicalWbc, the calculation time is shown in the following figure:
![2023-09-21 14-49-51屏幕截图](https://github.com/skywoodsz/qm_control/assets/58427883/91c06ba9-24d1-4a08-8911-db97c9afbe98)
This parameter was tested without changing any of your code. CPU is i7-1165.
When using WeightedWbc, the wbc calculation time is:
![2023-09-21 15-16-29屏幕截图](https://github.com/skywoodsz/qm_control/assets/58427883/d59ac207-fbbb-4bfe-b729-922df6324362)
I look forward to your reply very much.

**Comment by skywoodsz** [comment]
> Hello, this is a great project. Thank you for your open source project! During the process of running your project, I encountered a problem. Have you ever encountered a situation where the RealTIMeRector of Gazebo is very small, manifested as the robot moving in slow motion, as shown in the following figure: ![2023-09-21 14-49-01屏幕截图](https://user-images.githubusercontent.com/58427883/269519412-d9e9fadc-01fb-4ca5-9470-d54a4ae80ff1.png) Later, compared to legged_ Robot, it was found that it was caused by HierarchicalWbc, while WeightedWbc did not. When using HierarchicalWbc, the calculation time is shown in the following figure: ![2023-09-21 14-49-51屏幕截图](https://user-images.githubusercontent.com/58427883/269519448-91c06ba9-24d1-4a08-8911-db97c9afbe98.png) This parameter was tested without changing any of your code. CPU is i7-1165. When using WeightedWbc, the wbc calculation time is: ![2023-09-21 15-16-29屏幕截图](https://user-images.githubusercontent.com/58427883/269524323-d59ac207-fbbb-4bfe-b729-922df6324362.png) I look forward to your reply very much.

Thanks for your follow!
There is not the WeightedWbc in my project.
Did you build the project with RELEASE? You can try 
`catkin config -DCMAKE_BUILD_TYPE=RelWithDebInfo`.

**Comment by ChenZheng29** [comment]
Thank you for your reply!
Yes, I have already done this step, but it is not the problem caused by this step. Because I have no problem using WeightedWbc, while HierarchicalWbc only appears. If I didn't do this step, I have also tried, and it will always be in a slow state.
As for WeightedWbc, I ran it in legged_robot of 'qiayuanliao' and there was no problem. However, in his code, changing WeightedWbc to HierarchicalWbc would also cause the problem of slowing down.
I also found in your other [repository](https://github.com/skywoodsz/legged_control/tree/wbc) that you have made improvements to wbc, including testing the runtime of wbc under two algorithms. May I ask if you changed WeightedWbc to HierarchicalWbc during wbc instantiation without doing anything else? Just like this:
from:
![2023-09-21 19-23-39屏幕截图](https://github.com/skywoodsz/qm_control/assets/58427883/5a5b5cd5-92bf-45d8-826c-e4db5d8e9234)
to:
![2023-09-21 19-24-07屏幕截图](https://github.com/skywoodsz/qm_control/assets/58427883/c29004c1-de07-4c10-938a-135c068c2bec)

**Comment by skywoodsz** [comment]
> Thank you for your reply! Yes, I have already done this step, but it is not the problem caused by this step. Because I have no problem using WeightedWbc, while HierarchicalWbc only appears. If I didn't do this step, I have also tried, and it will always be in a slow state. As for WeightedWbc, I ran it in legged_robot of 'qiayuanliao' and there was no problem. However, in his code, changing WeightedWbc to HierarchicalWbc would also cause the problem of slowing down. I also found in your other [repository](https://github.com/skywoodsz/legged_control/tree/wbc) that you have made improvements to wbc, including testing the runtime of wbc under two algorithms. May I ask if you changed WeightedWbc to HierarchicalWbc during wbc instantiation without doing anything else? Just like this: from: ![2023-09-21 19-23-39屏幕截图](https://user-images.githubusercontent.com/58427883/269595423-5a5b5cd5-92bf-45d8-826c-e4db5d8e9234.png) to: ![2023-09-21 19-24-07屏幕截图](https://user-images.githubusercontent.com/58427883/269595506-c29004c1-de07-4c10-938a-135c068c2bec.png)

1. Have you tried running *MPC Only*?  *HierarchicalWbc* is also used in *MPC Only* with diffirent tasks. 
I guess the problem may be caused by the number of solutions to qpOASES being too large. You can try changing `int nWsr = 100;` to `int nWsr = 20;` in https://github.com/skywoodsz/qm_control/blob/bd8e249abc8ac759346abfbaeedf4d2a52e48d29/qm_wbc/src/HoQp.cpp#L141

2. No, it is dangerous to change the controller while the robot is running.

**Comment by ChenZheng29** [comment]
Changing nWsr from 100 to 20 also has no effect, using MPC Only will also cause slow motion.
Do you think there are any benefits of Hierarchical Wbc compared to Weighted Wbc? If it's similar, I'll just use WeightedWbc hahaha
In addition, I would like to ask why you still use wbc in your MPC Only? Isn't it enough to directly calculate the foot reaction force as joint torque?

**Comment by skywoodsz** [comment]
> Changing nWsr from 100 to 20 also has no effect, using MPC Only will also cause slow motion. Do you think there are any benefits of Hierarchical Wbc compared to Weighted Wbc? If it's similar, I'll just use WeightedWbc hahaha In addition, I would like to ask why you still use wbc in your MPC Only? Isn't it enough to directly calculate the foot reaction force as joint torque?

1. Well, HierarchicalWbc can achieve priority control, and there is no need to find weight parameters. But, if you have nice weight parameters, there is little difference between the HierarchicalWbc and WeightedWbc.
2. In the early stage of the project, I did not use WBC in *MPC Only*, so I took the name.  However, because WBC uses a more realistic dynamic model and higher control frequency, it can make the robot more stable, especially in the hardware robot.

**Comment by skywoodsz** [comment]
> Changing nWsr from 100 to 20 also has no effect, using MPC Only will also cause slow motion. Do you think there are any benefits of Hierarchical Wbc compared to Weighted Wbc? If it's similar, I'll just use WeightedWbc hahaha In addition, I would like to ask why you still use wbc in your MPC Only? Isn't it enough to directly calculate the foot reaction force as joint torque?

In addition, I did not add torque limits in the MPC formulation but added them in the WBC. There may be wrong when the robot is applied to a large force without WBC.

**Comment by ChenZheng29** [comment]
Okay, I have a general understanding. Thank you very much for your reply!!!
