### ISSUE TITLE
请问启动后机械狗趴着怎么站起来呢

### ISSUE THREAD

**Issue by dbdxnuliba** [skywoodsz/qm_control#6]
您好我遇到了机器人站立不起来不受手柄控制的情况，请帮看下，谢谢
我的操作步骤是：
1.roslaunch qm_gazebo empty_world_mpc.launch
然后点击gazebo的运行按钮效果如下
![image](https://github.com/skywoodsz/qm_control/assets/13350158/4f6d452b-9481-43f3-82bb-b8767e53a380)

然后运行2.roslaunch  qm_controllers load_controller.launch
![image](https://github.com/skywoodsz/qm_control/assets/13350158/abbead15-2fd2-4382-91bb-082b2b73b1df)

3.rosrun rqt_controller_manager rqt_controller_manager
![image](https://github.com/skywoodsz/qm_control/assets/13350158/83f5a43c-f29d-4068-8466-9506915ecc71)

4最后运行roslaunch qm_controllers load_qm_target.launch 
![image](https://github.com/skywoodsz/qm_control/assets/13350158/ec3cfb09-2a2e-443b-bdfd-b334b4782804)

然后按操作手柄，机器人趴着没有反映。
按照您的图片提示按的
![image](https://github.com/skywoodsz/qm_control/assets/13350158/c7438be5-14b6-4534-a71d-122b5ead9b36)

不过按手柄时终端打印了警告
[ WARN] [1695377080.657051865]: Couldn't set gain on joystick force feedback: Bad file descriptor
Gait "" not found
如图：
![image](https://github.com/skywoodsz/qm_control/assets/13350158/5e737315-2367-4217-a5fb-b6d0d1ace147)
我用的手柄是这样的：
![image](https://github.com/skywoodsz/qm_control/assets/13350158/e79fe677-409b-4191-a0bf-a017071fc206)
但是/joy话题是正常有的
![image](https://github.com/skywoodsz/qm_control/assets/13350158/acb6b874-8723-44af-90dc-cfc4114c808a)

然后rqt_graph看下节点图
![image](https://github.com/skywoodsz/qm_control/assets/13350158/820a5138-3dd1-4704-a35f-aab149363355)

烦请看下，应该怎么操作才能让机器人站起来呀

**Comment by skywoodsz** [comment]
> 您好我遇到了机器人站立不起来不受手柄控制的情况，请帮看下，谢谢 我的操作步骤是： 1.roslaunch qm_gazebo empty_world_mpc.launch 然后点击gazebo的运行按钮效果如下 ![image](https://user-images.githubusercontent.com/13350158/269904423-4f6d452b-9481-43f3-82bb-b8767e53a380.png)
> 
> 然后运行2.roslaunch qm_controllers load_controller.launch ![image](https://user-images.githubusercontent.com/13350158/269904633-abbead15-2fd2-4382-91bb-082b2b73b1df.png)
> 
> 3.rosrun rqt_controller_manager rqt_controller_manager ![image](https://user-images.githubusercontent.com/13350158/269904880-83f5a43c-f29d-4068-8466-9506915ecc71.png)
> 
> 4最后运行roslaunch qm_controllers load_qm_target.launch ![image](https://user-images.githubusercontent.com/13350158/269905095-ec3cfb09-2a2e-443b-bdfd-b334b4782804.png)
> 
> 然后按操作手柄，机器人趴着没有反映。 按照您的图片提示按的 ![image](https://user-images.githubusercontent.com/13350158/269908096-c7438be5-14b6-4534-a71d-122b5ead9b36.png)
> 
> 不过按手柄时终端打印了警告 [ WARN] [1695377080.657051865]: Couldn't set gain on joystick force feedback: Bad file descriptor Gait "" not found 如图： ![image](https://user-images.githubusercontent.com/13350158/269905278-5e737315-2367-4217-a5fb-b6d0d1ace147.png) 我用的手柄是这样的： ![image](https://user-images.githubusercontent.com/13350158/269905838-e79fe677-409b-4191-a0bf-a017071fc206.png) 但是/joy话题是正常有的 ![image](https://user-images.githubusercontent.com/13350158/269907262-acb6b874-8723-44af-90dc-cfc4114c808a.png)
> 
> 然后rqt_graph看下节点图 ![image](https://user-images.githubusercontent.com/13350158/269906969-820a5138-3dd1-4704-a35f-aab149363355.png)
> 
> 烦请看下，应该怎么操作才能让机器人站起来呀

Thanks for your follow!
1. `controllers/qm_controller_arm` is not loaded. If you first run this project, you should wait for a while to generate the controller. After the controller is successfully generated, there will be `controllers/qm_controller_arm`  item on `rqt_controller_manager`. For details, please refer to the video: [YouTube](https://youtu.be/JCn5obOh4D8), [bilibili](https://www.bilibili.com/video/BV1uP411v7Ab) (for China).
2. After the controller is successfully started, you can publish the desired position of the end effector on RVIZ to make the robot stand up.  Or you can press any enabled button (e.g., RB, LB) of the joy to make the robot stand up.

**Comment by dbdxnuliba** [comment]
收到，感谢指导，
