### ISSUE TITLE
robot fails to initialize while links' collision is added

### ISSUE THREAD

**Issue by SkyGuoGary** [skywoodsz/qm_control#9]
Thanks for your open source! 
This is such a great project that I wanna use it to finish more complex tasks. 
However, when I try adding the collision of the links of the robotic arm, it seems that the end effector couldn't reach the target pose while initializing. 
I have inputted these 3 command in proper order:
> roslaunch qm_gazebo door_world.launch
> roslaunch qm_controllers load_controller.launch
> rosrun rqt_controller_manager rqt_controller_manager

Then the robot keeps wobbling. More details are in the video below.
This would not happen when I don't set the col=TRUE in kinova_common.xacro. 

![2024-01-10 23-39-59 的屏幕截图](https://github.com/skywoodsz/qm_control/assets/125889716/256d104c-98e6-4a7f-b6c1-a29f4a58e547)

https://github.com/skywoodsz/qm_control/assets/125889716/9bf20799-8288-4e94-8ae1-682c6cabcaf9

Do you know how to solve this problem?

**Comment by skywoodsz** [comment]
@SkyGuoGary

Why don't you contact me by WeChat directly?

A simple solution is only adding collision property to the end-effector of the manipulator.
Or you can use the MPC-Only interface to control the robot.
